const references = [
	{"id": 1, "name": "Choose Your Dog App", "platform": "React", "image": "https://aranyrichard.hu/wp-content/uploads/2021/04/choose-your-dog.png", "url": "Nemzeti Szakképzési és Felnőttképzési Hivatal (NSZFH)", "description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus suscipit nisi vitae feugiat vestibulum. Aliquam porta nulla vel odio scelerisque, pretium volutpat dui euismod."},
	{"id": 2, "name": "LikeSpace Office Rental Startup Platform","platform": "Wordpress", "image": "https://aranyrichard.hu/wp-content/uploads/2021/04/likespace.png", "url": "AR Digital", "description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus suscipit nisi vitae feugiat vestibulum. Aliquam porta nulla vel odio scelerisque, pretium volutpat dui euismod."},
	{"id": 3, "name": "React and Morty App","platform": "React", "image": "https://aranyrichard.hu/wp-content/uploads/2021/04/react-and-morty.png", "url": "Playsic - The Social Music App", "description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus suscipit nisi vitae feugiat vestibulum. Aliquam porta nulla vel odio scelerisque, pretium volutpat dui euismod."},
	{"id": 4, "name": "Immunosoft One Product Webshop","platform": "Woocommerce", "image": "https://aranyrichard.hu/wp-content/uploads/2021/04/immunosoft.png", "url": "AR Digital", "description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus suscipit nisi vitae feugiat vestibulum. Aliquam porta nulla vel odio scelerisque, pretium volutpat dui euismod."},
	{"id": 5, "name": "Social Media Dashboard Frontend","platform": "React", "image": "https://aranyrichard.hu/wp-content/uploads/2021/04/social-media-dashboard.png", "url": "Kompel Kft.", "description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus suscipit nisi vitae feugiat vestibulum. Aliquam porta nulla vel odio scelerisque, pretium volutpat dui euismod."},
	{"id": 6, "name": "Szikra CoWorking Website","platform": "Wordpress", "image": "https://aranyrichard.hu/wp-content/uploads/2021/04/szikra.png", "url": "BeBrand Influencer Marketing Agency", "description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus suscipit nisi vitae feugiat vestibulum. Aliquam porta nulla vel odio scelerisque, pretium volutpat dui euismod."},
	{"id": 7, "name": "ToDo App Frontend","platform": "React", "image": "https://aranyrichard.hu/wp-content/uploads/2021/04/todo.png", "url": "Demera Kft.", "description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus suscipit nisi vitae feugiat vestibulum. Aliquam porta nulla vel odio scelerisque, pretium volutpat dui euismod."},
	{"id": 8, "name": "Szépségterasz Beauty Salon Website","platform": "Wordpress", "image": "https://aranyrichard.hu/wp-content/uploads/2021/04/szepsegterasz.png", "url": "Demera Kft.", "description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus suscipit nisi vitae feugiat vestibulum. Aliquam porta nulla vel odio scelerisque, pretium volutpat dui euismod."},
	{"id": 9, "name": "Istvan Nyari Artist Portfolio Site","platform": "Wordpress", "image": "https://aranyrichard.hu/wp-content/uploads/2021/04/istvan-nyari.png", "url": "Demera Kft.", "description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus suscipit nisi vitae feugiat vestibulum. Aliquam porta nulla vel odio scelerisque, pretium volutpat dui euismod."}
]

export default references;